name: TG Notification

'on':
  push:
    paths:
      - ip.txt
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read IP
        run: |
          echo "### Latest IP" > msg.md
          echo '\`\`\`' >> msg.md
          cat ip.txt >> msg.md || echo "no ip.txt"
          echo '\`\`\`' >> msg.md
          echo "" >> msg.md
          date >> msg.md
          cat msg.md

      - name: Send TG
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message_file: msg.md
          format: markdown
